# Generated by Django 5.2.17 on 2026-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Applied Linguistics & ELT', 'Applied Linguistics & ELT'), ('Cultural Studies & Literature', 'Cultural Studies & Literature'), ('Communication & Media', 'Communication & Media'), ('Translation Studies', 'Translation Studies'), ('Interdisciplinary Humanities', 'Interdisciplinary Humanities')], default='Applied Linguistics & ELT', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('portal_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(default='University Portal', max_length=100)),
                ('tests_info', models.TextField(blank=True, default='Pre-selection calculation + Written Concours + Oral Interview')),
                ('description', models.TextField(blank=True, default='')),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
